import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { StatusBadge } from "@/components/status-badge";
import { decideRequest } from "@/app/(protected)/actions";
import { isAdmin, requireProfile } from "@/lib/auth";
import { createClient } from "@/lib/supabase/server";
import { displayDate } from "@/lib/utils";
import { redirect } from "next/navigation";

export default async function RequestsPage({ searchParams }: { searchParams: Promise<{ message?: string }> }) { const profile = await requireProfile(); if (!isAdmin(profile)) redirect("/"); const { message } = await searchParams; const supabase = await createClient(); const { data } = await supabase.from("requests").select("id,asset_id,user_id,purpose,requested_from,requested_until,status,assets(name,asset_code),users!requests_user_id_fkey(name,email)").eq("status", "PENDING").order("created_at"); return <div className="space-y-5"><div><h1 className="text-3xl font-bold">Pending Requests</h1><p className="text-slate-600">Approve to check an asset out immediately.</p></div>{message && <p className="rounded-lg bg-green-50 p-3 text-sm text-green-700">✓ {message}</p>}<div className="space-y-3">{(data || []).map((request: any) => <Card key={request.id}><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-bold">{request.assets?.name}</h2><p className="text-sm text-slate-600">Requested by: {request.users?.name || request.users?.email}</p><p className="mt-2 text-sm">{request.purpose}</p><p className="mt-2 text-xs text-slate-500">{displayDate(request.requested_from)} · Return {displayDate(request.requested_until)}</p></div><StatusBadge status="PENDING"/></div><div className="mt-4 flex gap-2"><form action={decideRequest}><input type="hidden" name="request_id" value={request.id}/><input type="hidden" name="decision" value="approve"/><Button>Approve & Check Out</Button></form><details><summary className="inline-flex min-h-11 cursor-pointer items-center rounded-lg border px-4 py-2 font-semibold">Reject</summary><form action={decideRequest} className="mt-2 flex gap-2"><input type="hidden" name="request_id" value={request.id}/><input type="hidden" name="decision" value="reject"/><input name="reason" placeholder="Optional reason" className="w-40 rounded-lg border px-3"/><Button variant="danger">Confirm</Button></form></details></div></Card>)}</div>{!data?.length && <Card className="text-center text-slate-600">No pending requests.</Card>}</div>; }
